server:
  port: 50001

spring:
  datasource:
    url: jdbc:h2:file:~/test
    data-username: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
